version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: CohesionX_UserManagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Itachi007!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  cohesionx.usermanagement:
    image: ${DOCKER_REGISTRY-}cohesionxusermanagement
    build:
      context: .
      dockerfile: CohesionX.UserManagement/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5090:5090"
      - "5091:5091"
    environment:
      # Database Options
      DatabasesOptions__PostgreSQLConnectionString: "Host=postgres;Port=5432;Database=CohesionX_UserManagement;Username=postgres;Password=Itachi007!"
      
      # Redis Options
      RedisConfiguration__ConnectionString: "redis:6379"
      RedisConfiguration__DatabaseId: "0"
      RedisConfiguration__ConnectTimeout: "60000"
      RedisConfiguration__SyncTimeout: "60000"
      RedisConfiguration__ConnectRetry: "3"
      RedisConfiguration__ReconnectRetryPolicy: "3"
      
      # Identity Server
      IdentityServerOptions__Authority: "https://dev.vectormind.chat/security"
      IdentityServerOptions__ApiName: "api"

      # App Constants
      AppConstantsOptions__EnableGrpc: "false"
      AppConstantsOptions__EnableIdDocumentCollection: "true"
      AppConstantsOptions__PopiaComplianceMode: "strict"
      AppConstantsOptions__InitialEloRating: "1200"
      AppConstantsOptions__MinEloRequiredForPro: "1600"
      AppConstantsOptions__MinJobsRequiredForPro: "500"
      AppConstantsOptions__EloKFactorNew: "32"
      AppConstantsOptions__EloKFactorEstablished: "24"
      AppConstantsOptions__EloKFactorExpert: "16"
      AppConstantsOptions__JobTimeoutHours: "4"
      AppConstantsOptions__MaxConcurrentJobs: "3"
      AppConstantsOptions__RedisCacheTtlMinutes: "360"
      AppConstantsOptions__DefaultBookoutMinutes: "480"

      # Workflow Engine
      WorkflowEngineOptions__BaseUri: "https://workflow-engine-service"
      WorkflowEngineOptions__EloNotifyUri: "https://workflow-engine-service"

      # OpenTelemetry
      OpenTelemetryOptions__ServiceName: "UserManagement"
      OpenTelemetryOptions__ServiceVersion: "1.0.0"
      OpenTelemetryOptions__AzureApplicationInsightsConnStr: "<azure_conn_str>"

      # JWT
      JwtOptions__Secret: "0fb7d3a1e50741308310b58d75e16a92a1556b8b2a41c80a8dc9e8a8715bc5ef"
      JwtOptions__Issuer: "CohesionX.UserManagement"
      JwtOptions__ExpiryMinutes: "60"

      # Validation
      ValidationOptions__RequireIdDocument: "true"
      ValidationOptions__RequirePhotoUpload: "true"
      ValidationOptions__RequirePhoneVerification: "true"
      ValidationOptions__RequireEmailVerification: "true"
      ValidationOptions__VerificationLevel: "basic_v1"
      ValidationOptions__ValidationRules__IdNumber: "format_validation_only"
      ValidationOptions__ValidationRules__photo: "presence_check_only"
      ValidationOptions__ValidationRules__note: "V2_will_add_dha_verification"
      ValidationOptions__Reason: "PII_compliance_SA_POPIA_with_basic_validation"

      # ASP.NET Core Defaults
      AllowedHosts: "*"
      ASPNETCORE_HTTP_PORTS: 5090
      ASPNETCORE_HTTPS_PORTS: 5091
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
